<a href="https://colab.research.google.com/github/DanyelMorales/MinesRocks/blob/main/solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
import os
import lib.digit_classifier

sonar_original = "dataset/sonar.all-data"
sonar_well_balanced = "cache/rocks_mines.csv"
data_df = None
if os.path.exists(sonar_well_balanced):
    print("Loading sonar well balanced dataset")
    data_df = pd.read_csv(sonar_well_balanced, header=None)
else:
    print("Loading sonar original dataset")
    data_df = pd.read_csv(sonar_original, header=None)
data_df.head()

Loading sonar well balanced dataset


0       1       2       3       4       5       6       7       8   \
0  0.0000  1.0000  2.0000  3.0000  4.0000  5.0000  6.0000  7.0000  8.0000   
1  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428   
2  0.0217  0.0340  0.0392  0.0236  0.1081  0.1164  0.1398  0.1009  0.1147   
3  0.0131  0.0387  0.0329  0.0078  0.0721  0.1341  0.1626  0.1902  0.2610   
4  0.0249  0.0119  0.0277  0.0760  0.1218  0.1538  0.1192  0.1229  0.2119   

       9   ...       51       52       53       54       55       56       57  \
0  9.0000  ...  51.0000  52.0000  53.0000  54.0000  55.0000  56.0000  57.0000   
1  0.2227  ...   0.0098   0.0178   0.0077   0.0074   0.0095   0.0055   0.0045   
2  0.1777  ...   0.0031   0.0103   0.0078   0.0077   0.0094   0.0031   0.0030   
3  0.3193  ...   0.0150   0.0076   0.0032   0.0037   0.0071   0.0040   0.0009   
4  0.2531  ...   0.0027   0.0068   0.0150   0.0012   0.0133   0.0048   0.0244   

        58       59  60  
0  58.0000  59.0000  60  
1   0.0063   0.0039   M  
2   0.0013   0.0069   R  
3   0.0015   0.0085   M  
4   0.0077   0.0074   M  

[5 rows x 61 columns]

In [3]:
if os.path.exists(sonar_well_balanced):
    data_df = shuffle(data_df)
data_np = data_df.to_numpy()
data_np.shape

(212, 61)

In [4]:
data_np

array([[0.0253, 0.0808, 0.0507, ..., 0.0081, 0.0053, 'R'],
       [0.031, 0.0221, 0.0433, ..., 0.0067, 0.0054, 'M'],
       [0.0158, 0.0239, 0.015, ..., 0.0022, 0.0021, 'M'],
       ...,
       [0.0131, 0.0201, 0.0045, ..., 0.0029, 0.0053, 'M'],
       [0.0125, 0.0152, 0.0218, ..., 0.0086, 0.0058, 'R'],
       [0.0201, 0.0165, 0.0344, ..., 0.0082, 0.0036, 'M']], dtype=object)

In [5]:
from lib.ClassifierHelper import Classifier
from lib.mnist import prepend_bias, extract_test_data
from lib.Encoding.encoding import EncodeHelper
from lib.Encoding.EncodingEnum import Strategy
from lib.Encoding.EncodingConfig import CustomEncoding


In [6]:
X_train, Y_train, X_test, Y_test = extract_test_data(data_np)

test_size: 49
[[0.0253 0.0808 0.0507 ... 0.0081 0.0053 'R']
 [0.031 0.0221 0.0433 ... 0.0067 0.0054 'M']
 [0.0158 0.0239 0.015 ... 0.0022 0.0021 'M']
 ...
 [0.0116 0.0744 0.0367 ... 0.0057 0.0035 'M']
 [0.0378 0.0318 0.0423 ... 0.0043 0.0053 'R']
 [0.0856 0.0454 0.0382 ... 0.0037 0.0037 'R']]


In [7]:

encodeStrategy = CustomEncoding(lambda x: 1 if x == 'M' else 0, lambda x: 'M' if round(x) == 1 else 'R',
                                Strategy.REPLACE_LABEL_BY_VALUE)
encodeHelper = EncodeHelper(encodingStrategy=encodeStrategy)
Y_train = encodeHelper.one_hot_encoding(Y_train)
X_train = prepend_bias(X_train)
X_test = prepend_bias(X_test)

In [8]:
Y_train = Y_train.astype(np.int64)
X_train = X_train.astype(np.float64)
X_test = X_test.astype(np.float64)

In [9]:
print(Y_train.dtype)
print(X_train.dtype)
print(X_test.dtype)

int64
float64
float64


In [10]:
Y_train

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [11]:
X_train

array([[1.00e+00, 3.68e-02, 2.79e-02, ..., 8.60e-03, 1.10e-02, 5.20e-03],
       [1.00e+00, 5.00e-03, 1.70e-03, ..., 6.30e-03, 1.70e-03, 2.80e-03],
       [1.00e+00, 2.60e-02, 1.92e-02, ..., 8.00e-04, 4.40e-03, 7.70e-03],
       ...,
       [1.00e+00, 1.31e-02, 2.01e-02, ..., 6.60e-03, 2.90e-03, 5.30e-03],
       [1.00e+00, 1.25e-02, 1.52e-02, ..., 4.10e-03, 8.60e-03, 5.80e-03],
       [1.00e+00, 2.01e-02, 1.65e-02, ..., 1.05e-02, 8.20e-03, 3.60e-03]])

In [12]:
X_test

array([[1.    , 0.0253, 0.0808, ..., 0.0039, 0.0081, 0.0053],
       [1.    , 0.031 , 0.0221, ..., 0.0056, 0.0067, 0.0054],
       [1.    , 0.0158, 0.0239, ..., 0.0046, 0.0022, 0.0021],
       ...,
       [1.    , 0.0116, 0.0744, ..., 0.0044, 0.0057, 0.0035],
       [1.    , 0.0378, 0.0318, ..., 0.0062, 0.0043, 0.0053],
       [1.    , 0.0856, 0.0454, ..., 0.0102, 0.0037, 0.0037]])

In [13]:
Y_test

array(['R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M',
       'M', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'M', 'R', 'R', 'M',
       'R', 'R', 'M', 'R', 'M', 'M', 'M', 'M', 'R', 'R'], dtype=object)

In [14]:
classifier = Classifier(encodeHelper)
lib.digit_classifier.useArgmax = False
lib.ClassifierHelper.is_binary_classification = True
lib.ClassifierHelper.apply_ravel = True
w, historyW = classifier.train(X_train, Y_train, X_test, Y_test, iterations=700, lr=0.01)

Starting Digit Classifier...
Using useArgmax=False
0 - Loss: 0.6931471805599454 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
1 - Loss: 0.6765699269254326 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
2 - Loss: 0.6764163720331673 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
3 - Loss: 0.6762640877768221 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
4 - Loss: 0.6761130273620112 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
5 - Loss: 0.6759631458899057 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
6 - Loss: 0.6758144002699552 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
7 - Loss: 0.6756667491368095 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
8 - Loss: 0.6755201527713368 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
9 - Loss: 0.6753745730256374 - examples: 49, 
 34.69387755102041%
Using useArgmax=False
10 - Loss: 0.675229973251947 - examples: 49, 
 34.69387755102041%
Usi

In [15]:
pct_success = classifier.test(X_test, Y_test, w)
pct_success

Using useArgmax=False
Success: 30/49 61.224489795918366%


61.224489795918366

In [16]:
# from lib.graph import graph_loss
# graph_loss(historyW)

[array([[-0.02521672],
       [ 0.02107294],
       [ 0.01955137],
       [ 0.02034946],
       [ 0.03342783],
       [ 0.03500131],
       [ 0.01522049],
       [ 0.01727958],
       [ 0.03586966],
       [ 0.09658048],
       [ 0.11995596],
       [ 0.15329918],
       [ 0.14867941],
       [ 0.10744267],
       [ 0.03572288],
       [-0.00858523],
       [-0.05547584],
       [-0.09816966],
       [-0.0723828 ],
       [ 0.04841953],
       [ 0.12682564],
       [ 0.13701583],
       [ 0.09330349],
       [ 0.04941201],
       [ 0.02893535],
       [ 0.0083282 ],
       [ 0.02341286],
       [ 0.03852922],
       [ 0.05101907],
       [-0.00465931],
       [-0.04598188],
       [-0.12133082],
       [-0.08223792],
       [-0.11754935],
       [-0.15491006],
       [-0.20693456],
       [-0.2583878 ],
       [-0.2066688 ],
       [-0.04650009],
       [ 0.02920611],
       [-0.02526654],
       [ 0.005263  ],
       [ 0.05236297],
       [ 0.08721228],
       [ 0.07902503],
       [ 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (700, 2) + inhomogeneous part.

In [ ]:
weight_file_name = 'cache/rocks_mines_weights' + str(pct_success) + '.npy'
if pct_success > 70:
    print("Pct success >= 70%")
    np.save(weight_file_name, w)
    if os.path.exists(sonar_well_balanced):
        data_df.to_csv('cache/rocks_mines.csv', index=False)
    else:
        print(f'{sonar_well_balanced} already exists, not overriding it, creating a new one')
        data_df.to_csv('cache/rocks_mines' + pct_success + '.csv', index=False)

In [ ]:
if pct_success > 70:
    loaded_arr = np.load(weight_file_name)
    classifier.test(X_test, Y_test, loaded_arr)
